apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "helmchart-replicaset.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helmchart-replicaset.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "helmchart-replicaset.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 80
